name: Build and Test

on:
    pull_request:
        branches: [main, development]
    workflow_dispatch:

jobs:
    build-erdjs:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run compile
            - run: npm test
